// Build script (like levels/convert-levels.ts) - assembles the daily pool and writes
// levels/DailyPool.ts. Two sources:
// 1. Community pack levels (Levels/levelsCommunity.xml) that have a hand-recorded `solution` -
//    trusted the same way Easy/Medium/Hard's own Optimal arrays already are (not independently
//    re-solved from scratch - a spot check found some of these take 30+ seconds each to verify).
//    ALL of these are kept regardless of move count, including short ones - they're already
//    human-verified, unlike generated candidates (see MIN_MOVES below). Ones with NO recorded
//    solution at all were tried with a generous budget and still not solved within a couple of
//    minutes each, so those stay excluded rather than guessed at.
// 2. Freshly generated levels (lib/proceduralGenerator.ts) to fill whatever's left in each tier -
//    never accepted below MIN_MOVES (a <5-move puzzle was judged too trivial to be worth a slot).
//
// Difficulty tiers (by measured/recorded optimal move count): Easy <=7, Medium 8-11, Hard >=12.
// Procedural generation reliably produces puzzles up to ~10-11 moves but rarely more (the search
// finds an easy way out long before exhausting a large candidate's real difficulty) - Hard gets a
// much larger per-candidate solve budget (HARD_SOLVE_TIME_MS) to dig deeper than before, and still
// leans on Community's naturally longer solutions (12-31 moves) to fill out the tier.
//
//   npx ts-node --transpile-only -r ./levels/cssStub.js -r tsconfig-paths/register -O '{"module":"commonjs","jsx":"react"}' levels/build-daily-pool.ts

import fs from "fs";
import {decodeXmlLevel} from "@/levels/xmlLevelDecoder";
import {generateLevel} from "@/lib/proceduralGenerator";
import {encodeLevel, type CompactLevel} from "@/lib/levelFormat";
import type {ScoredPack} from "@/lib/scoring";
import type {Level} from "@/lib/gameEngine";

const TARGET_PER_TIER = 100;
const COMMUNITY_COUNT = 58;
const MIN_MOVES = 5; // generated candidates below this are discarded as too simple

function classify(moves: number): ScoredPack {
  if (moves <= 7) return "Easy";
  if (moves <= 11) return "Medium";
  return "Hard"; // 12+
}

type PoolCandidate = {level: Level; optimal: number; difficulty: ScoredPack; source: string};

const buckets: Record<ScoredPack, Array<PoolCandidate>> = {Easy: [], Medium: [], Hard: []};

// --- Source 1: Community levels with a recorded solution - ALL of them, any move count ---------
for (let i = 0; i < COMMUNITY_COUNT; i++) {
  const {level, solutionMoves} = decodeXmlLevel("Levels/levelsCommunity.xml", i);
  if (solutionMoves === null) continue;
  const difficulty = classify(solutionMoves);
  buckets[difficulty].push({level, optimal: solutionMoves, difficulty, source: `community#${i}`});
}
console.log(`Community contributed: Easy=${buckets.Easy.length} Medium=${buckets.Medium.length} Hard=${buckets.Hard.length}`);

type RawEntry = {c: CompactLevel; o: number; d: ScoredPack};

function writePoolFile() {
  const all = [...buckets.Easy, ...buckets.Medium, ...buckets.Hard];
  const raw: Array<RawEntry> = all.map((c) => ({c: encodeLevel(c.level), o: c.optimal, d: c.difficulty}));
  const output = `// Generated by levels/build-daily-pool.ts - DO NOT EDIT BY HAND. Re-run that script to rebuild.
// ${all.length} levels: ${buckets.Easy.length} Easy, ${buckets.Medium.length} Medium, ${buckets.Hard.length} Hard.
// Sourced from Community pack levels with a verified hand-authored solution, topped up by
// procedurally generated ones (lib/proceduralGenerator.ts) - see that file and this one for how.
import {decodeLevel, type CompactLevel} from "@/lib/levelFormat";
import type {Level} from "@/lib/gameEngine";
import type {ScoredPack} from "@/lib/scoring";

export type PoolEntry = {level: Level; optimal: number; difficulty: ScoredPack};

type RawEntry = {c: CompactLevel; o: number; d: ScoredPack};

const RAW: Array<RawEntry> = ${JSON.stringify(raw)};

export const DailyPool: Array<PoolEntry> = RAW.map((r) => ({level: decodeLevel(r.c), optimal: r.o, difficulty: r.d}));

// Bumped on every rebuild - a rebuild reorders/replaces entries, so a poolIndex saved by a client
// before a rebuild can silently point at a different (or, if the pool shrank, out-of-range) level
// afterward. lib/dailyLevels.ts compares this against what a client last saw and regenerates
// *today's* (never-completed) picks rather than let that happen - see its ensureTodayEntry().
export const DAILY_POOL_VERSION = "${Date.now()}";
`;
  fs.writeFileSync("levels/DailyPool.ts", output);
  console.log(`wrote levels/DailyPool.ts (${all.length} levels: Easy=${buckets.Easy.length} Medium=${buckets.Medium.length} Hard=${buckets.Hard.length})`);
}
writePoolFile(); // community-only baseline, in case generation is interrupted immediately

// --- Source 2: procedural generation to fill the rest -------------------------------------------
// Easy/Medium (5-11 moves) both come from the same "Medium" board profile (bigger than "Easy"'s -
// the small Easy profile rarely clears 5 moves at all) and are classified post-hoc into whichever
// of the two tiers they land in. Hard uses the "Hard" profile with a much larger per-candidate
// solve budget - 120s, one candidate at a time (maxAttempts=1) - rather than many candidates each
// with a small budget, so the search gets real time to dig into one board instead of bailing early
// on all of them.
const EASY_MEDIUM_SOLVE_BUDGET = {maxDepth: 20, maxStates: 60000, maxTimeMs: 8000};
const HARD_SOLVE_TIME_MS = 120000;
const HARD_SOLVE_BUDGET = {maxDepth: 35, maxStates: 2000000, maxTimeMs: HARD_SOLVE_TIME_MS};

function runTier(label: string, profile: ScoredPack, minMoves: number, innerAttempts: number, solveBudget: typeof EASY_MEDIUM_SOLVE_BUDGET, tiersToFill: Array<ScoredPack>, maxTimeMs: number, logEvery: number) {
  let attempts = 0;
  const startedAt = Date.now();
  const stillNeeded = () => tiersToFill.some((t) => buckets[t].length < TARGET_PER_TIER);
  while (stillNeeded() && Date.now() - startedAt < maxTimeMs) {
    attempts++;
    const result = generateLevel(profile, innerAttempts, minMoves, solveBudget);
    if (result) {
      const difficulty = classify(result.optimal);
      if (buckets[difficulty].length < TARGET_PER_TIER) {
        buckets[difficulty].push({level: result.level, optimal: result.optimal, difficulty, source: "generated"});
      }
    }
    if (attempts % logEvery === 0 || (label === "Hard" && attempts % 5 === 0)) {
      console.log(`  [${label}] attempt ${attempts}: Easy=${buckets.Easy.length} Medium=${buckets.Medium.length} Hard=${buckets.Hard.length} (${((Date.now() - startedAt) / 1000).toFixed(0)}s)`);
      writePoolFile();
    }
  }
  console.log(`[${label}] done after ${attempts} attempts in ${((Date.now() - startedAt) / 1000).toFixed(0)}s`);
  writePoolFile();
}

runTier("Easy+Medium", "Medium", MIN_MOVES, 200, EASY_MEDIUM_SOLVE_BUDGET, ["Easy", "Medium"], 20 * 60 * 1000, 50);
// Most single candidates actually resolve in milliseconds (BFS finds a short true-minimum fast,
// even when it's below minMoves and gets rejected) - the 120s cap only matters for the rare one
// whose true minimum is genuinely deep, so generateLevel can burn through thousands of cheap
// candidates within the wall-clock budget below rather than being limited to a few hundred.
runTier("Hard", "Hard", Math.max(MIN_MOVES, 10), 3000, HARD_SOLVE_BUDGET, ["Hard"], 25 * 60 * 1000, 1);

console.log(`\nFinal pool: Easy=${buckets.Easy.length} Medium=${buckets.Medium.length} Hard=${buckets.Hard.length}`);
